name: Build

on:
  push:
    branches:
      - dev
      - master
      - release-*
      - 1.*
  pull_request:
    branches:
      - dev
      - master
      - release-*
      - 1.*
jobs:
  build:
    runs-on: [self-hosted, uid-runner]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and tests
        run: ./mvnw -B clean verify -Pe2e,integration-test

      - name: Send message to Slack channel
        if: ${{ failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master') }}
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: 'CFD1SMX7V'
          payload: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": ":x: Build on branch ${{github.ref}} failed in UI-Designer."
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "More details about the error <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true| here>"
            			}
            		}
            	]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
