name: Crowdin upload files

# Triggers the workflow every night
on:
  schedule:
    - cron: '0 3 * * *'

  workflow_dispatch:
    inputs:

jobs:
  devUpload:
    name: Crowdin upload
    strategy:
      max-parallel: 1
    runs-on: [self-hosted, uid-runner]
    steps:
      - name: Extract parameter
        id: init
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]
          then
              echo ::set-output name=baseBranch::${GITHUB_REF#refs/*/}
          else
              echo "##[set-output name=baseBranch;]$(echo dev)"
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.init.outputs.baseBranch }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install gettext
        run: sudo apt-get install gettext
      - name: Run Crowdin upload
        shell: bash
        run: ./infrastructure/crowdin/upload.sh --crowdin-api-key=${{ secrets.CROWDIN_API_KEY }} --branch=${{ steps.init.outputs.baseBranch }} --crowdin-project=bonita
      - name: Send message to Slack channel
        if: ${{ failure() }}
        uses: bonitasoft/actions/packages/notify-slack@1.1.0
        with:
          CHANNEL_ID: ${{ secrets.SLACK_UID_CHANNEL_ID }}
          MESSAGE: ":x: Upload dev crowdin keys failed in UI-Designer."
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


