name: Crowdin upload files for master

# Triggers the workflow every night
on:
  schedule:
    - cron: '0 4 * * *'

  workflow_dispatch:
    inputs:

jobs:
  devUpload:
    name: Crowdin upload
    strategy:
      max-parallel: 1
    runs-on: self-hosted
    steps:
      - name: Extract parameter
        id: init
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]
          then
              echo ::set-output name=baseBranch::${GITHUB_REF#refs/*/}
          else
              echo "##[set-output name=baseBranch;]$(echo master)"
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.init.outputs.baseBranch }}
      - uses: actions/setup-node@v2
        with:
          # Mandatory to use a old node version with our actual dependencies
          node-version: '14'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install gettext
        run: sudo apt-get install gettext
      - name: Run Crowdin upload
        shell: bash
        run: ./infrastructure/crowdin/upload.sh --crowdin-api-key=${{ secrets.CROWDIN_API_KEY }} --branch=${{ steps.init.outputs.baseBranch }} --crowdin-project=bonita
      - name: Send message to Slack channel
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: 'CFD1SMX7V'
          payload: |
            {
              "blocks": [
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": ":x: Upload master crowdin key failed in UI-Designer."
                      }
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "More details about the error <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true| here>"
                      }
                  }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

