name: Crowdin download files

# Triggers the workflow every night
on:
  schedule:
    - cron: '0 4 * * *'

  workflow_dispatch:
    inputs:

jobs:
  devDownload:
    name: Crowdin download on dev
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'dev'
      # Runs Crowdin download
      - name: Run Crowdin download
        run: ./infrastructure/crowdin/download.sh --crowdin-api-key=${{ secrets.CROWDIN_API_KEY }} --github-api-key=${{ secrets.GITHUB_TOKEN }}
