name: Merge branches
on:
  workflow_dispatch:
    inputs:
      from:
        description: Merge branch
        default: "master"
        required: true
      target:
        description: into
        default: "dev"
        required: true
jobs:
  merge-branches:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Merge ${{ github.event.inputs.from }} ->  ${{ github.event.inputs.target }}
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ${{ github.event.inputs.from }}
          target_branch: ${{ github.event.inputs.target }}
          github_token: ${{ secrets.GH_PERSONNAL_ACCES_TOKEN }}
      - name: Send message to Slack channel
        if: ${{ failure()}}
        uses: bonitasoft/notify-slack-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          channel-id: ${{ vars.UID_SLACK_CHANNEL_ID }}
          message: ":x: Merge ${{ github.event.inputs.from }} into ${{ github.event.inputs.target }} failed."
