name: Publish Artefacts

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: base tag version to publish
        default: 1.11.100
        required: true
      pushMavenCentral:
        description: true to push on artifactory
        default: false
        required: true
  repository_dispatch:
    types: [ github-publish ]

jobs:
  publishBinaries:
    name: Build, publish and upload binaries
    runs-on: [self-hosted, uid-runner]
    steps:
      - name: Extract parameter
        id: init
        run: |
          if [ ${{ github.event.action }} == 'github-publish' ]
            then
                echo "##[set-output name=tagVersion;]$(echo ${{ github.event.client_payload.releaseVersion }})"
                echo "##[set-output name=studioBaseBranch;]$(echo ${{ github.event.client_payload.studioBaseBranch }})"
            else
                echo "##[set-output name=tagVersion;]$(echo ${{ github.event.inputs.releaseVersion }})"
                echo "##[set-output name=studioBaseBranch;]$(echo ${{ github.ref }})"
                echo "##[set-output name=pushMavenCentral;]$(echo ${{ github.event.inputs.pushMavenCentral == 'true' }})"
            fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.init.outputs.tagVersion }}

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish artefact
        if: ${{ success() && ( github.event.action == 'github-publish' || steps.init.outputs.pushMavenCentral == 'true')}}
        run: ./mvnw deploy -DskipTests -DaltDeploymentRepository=bonita.releases::default::http://artifacts.rd.lan/maven/internal.releases/

      - name: Build binaries
        if: ${{ success() && ( github.event.action != 'github-publish' &&  steps.init.outputs.pushMavenCentral != 'true')}}
        run: ./mvnw -B package --file pom.xml -DskipTests

      - name: Send message to Slack channel
        if: ${{ success() && ( github.event.action == 'github-publish' ||  steps.init.outputs.pushMavenCentral == 'true')}}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref
          custom_payload: |
            {
              username: 'uid-release',
              icon_emoji: ':rocket:',
              attachments: [{
                color: 'good',
                text: `UI-Designer release ${{ steps.init.outputs.tagVersion }} successfully. You can open a PR on studio repository if needed`,
              }]
            }
        env:
               SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
