name: Publish Artefacts

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: base tag version to publish
        default: 1.12.X
        required: true
      pushMavenCentral:
        description: true to push on artifactory
        default: false
        required: true
  repository_dispatch:
    types: [ github-publish ]

jobs:
  publishBinaries:
    name: Build, publish and upload binaries
    runs-on: [self-hosted, uid-runner]
    steps:
      - name: Extract parameter
        id: init
        run: |
          if [ ${{ github.event.action }} == 'github-publish' ]
            then
                echo "##[set-output name=tagVersion;]$(echo ${{ github.event.client_payload.releaseVersion }})"
                echo "##[set-output name=branchToRelease;]$(echo ${{ github.event.client_payload.ref }})"
            else
                echo "##[set-output name=tagVersion;]$(echo ${{ github.event.inputs.releaseVersion }})"
                echo "##[set-output name=branchToRelease;]$(echo ${{ github.ref }})"
                echo "##[set-output name=pushMavenCentral;]$(echo ${{ github.event.inputs.pushMavenCentral == 'true' }})"
            fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.init.outputs.tagVersion }}

      - name: Set up Java 11
        if: ${{ steps.init.outputs.branchToRelease == 'refs/heads/master' || steps.init.outputs.branchToRelease == 'refs/heads/dev'}}
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # When repository-dispatch is called, default branch is always trigger, that's why we configure java 8 here for 1.12.x branch
      - name: Set up Java 8
        if: ${{ steps.init.outputs.branchToRelease  == 'refs/heads/1.12.x' &&  github.event.action == 'github-publish' }}
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Publish artefact
        if: ${{ success() && ( github.event.action == 'github-publish' || steps.init.outputs.pushMavenCentral == 'true')}}
        run: ./mvnw deploy -DskipTests -DaltDeploymentRepository=bonita.releases::default::http://artifacts.rd.lan/maven/internal.releases/

      - name: Build binaries
        if: ${{ success() && ( github.event.action != 'github-publish' &&  steps.init.outputs.pushMavenCentral != 'true')}}
        run: ./mvnw -B package --file pom.xml -DskipTests

      - name: Send message to Slack channel
        if: ${{ success() && ( github.event.action == 'github-publish' ||  steps.init.outputs.pushMavenCentral == 'true')}}
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: 'CFD1SMX7V'
          payload: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": ":white_check_mark: UI-Designer release ${{ steps.init.outputs.tagVersion }} successfully. You can open a PR on studio repository if needed :mini-gg:"
            			}
            		}
            	]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
