name: Update version
# Use this action to update version of ui-designer
# Is running on each release of uid
# and alone when we release a new major version
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to bump (By convention, just update minor version)
        default: 1.14.0
        required: true

jobs:
  updateVersion:
    name: Update UID version
    runs-on: ubuntu-22.04
    steps:
      - name: Setup checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONNAL_ACCES_TOKEN }}
      - uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
      - name: Config git
        run: |
          git config pull.rebase true

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Update Version
        shell: bash
        run: |
          ./infrastructure/update-version.sh ${{ github.event.inputs.version }}
          git commit -a -m "chore(versioning) update version to ${{ github.event.inputs.version }}"
          git push origin ${{ steps.extract_branch.outputs.branch }}

      - name: Send message to Slack channel
        if: ${{ failure() }}
        uses: bonitasoft/actions/packages/notify-slack@1.1.0
        with:
          CHANNEL_ID: ${{ secrets.SLACK_UID_CHANNEL_ID }}
          MESSAGE: ":x: :scream: UI-Designer update-version ${{ steps.newTagVersion.outputs.value }} failed."
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
